name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: cd server/unittests && make tests
    - name: build
      run: cd server && make && timeout 30 ./webserv

